name: PixelEmpires
version: ${project.version}
main: me.sucrosedev.pixelempires.PixelEmpires
api-version: 1.13
commands:
  join:
    description: Join world
  lobby:
    description: Teleport to lobby
  broadcast:
    description: Broadcast argument
  smite:
    description: Smite given player if they exist
  silent-tp:
    description: Silent tp command
  invisible:
    description: Toggles player invisibility
  flyspeed:
    description: Set flight speed
  takecoins:
    description: Take coins from specified player
  givecoins:
    description: Create and give new coins to specified player
  pay:
    description: Transact Pixel Coins
  balance:
    description: Get current balance
  shrine:
    description: Get closest shrine
  dungeon:
    description: Command for testing dungeon